---
- name: install GIT
  yum:
    name: git
    state: present
  become: true  
- name: Install ProxySQL deb file
  copy:
    src: /etc/ansible/"https://github.com/sysown/proxysql/releases/download/v1.4.12/proxysql-1.4.12-1-centos7.x86_64.rpm"
#    "https://github.com/sysown/proxysql/releases/download/v{{ proxysql_version }}/proxysql_{{ proxysql_version }}-centos7.x86_64.rpm"
    dest: /etc/ansible/proxysql-1.4.12-1-centos7.x86_64.rpm
- name: Install package.
  yum:
     name: /tmp/proxysql-2.0.10-1-centos7.x86_64.rpm
     state: present
  become: true
- name: Download MySQL client
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - mysql-client
    - python-mysqldb
