---
- name: install GIT
  yum:
    name: git
    state: present
  become: true  
- name: Install ProxySQL deb file
  copy:
    #src: "https://github.com/sysown/proxysql/releases/download/v{{ proxysql_version }}/proxysql_{{ proxysql_version }}-centos7.x86_64.rpm"
    #src: "https://github.com/sysown/proxysql/releases/download/v2.0.10/proxysql-2.0.10-1-centos7.x86_64.rpm"
    src: https://github.com/sysown/proxysql/releases/download/v{{ proxysql_version }}/proxysql_{{ proxysql_version }}-centos7.x86_64.rpm
    dest: /tmp/proxysql-2.0.10-1-centos7.x86_64.rpm
- name: Install package.
  yum:
     name: /tmp/package.rpm
     state: present
  become: true
- name: Download MySQL client
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - mysql-client
    - python-mysqldb
