---
- name: Install ProxySQL deb file
  yum:
    rpm: "https://github.com/sysown/proxysql/releases/download/v{{ proxysql_version }}/proxysql_{{ proxysql_version }}-centos7.x86_64.rpm"
    state: present
  become: true

- name: Download MySQL client
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - mysql-client
    - python-mysqldb
